### PR TITLE
color picker + misc bug fix

### LINKED ISSUE #44: Choosing a color currently is broken on mobile-sized windows
After the changes in #42, there's an issue with the color picker. I reverted the deployed version for now until this is fixed.

### PR DESCRIPTION
**Pull request by hiddenist**
This fixes an issue where, when selecting a color on mobile, the canvas is cleared out on the next draw.

It also fixes an issue where color history was not being populated.

Closes #44

### CODE REVIEW

**Comment by hiddenist** [comment]
note for myself: https://github.com/hiddenist/drawing-app/actions/runs/7156473524

File: libs/drawing-engine/src/engine/Layer.ts [hunk 1]
```diff
@@ -46,8 +46,7 @@ export class Layer {
       gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true)
       gl.texImage2D(target, level, internalFormat, srcFormat, srcType, croppedSource)
     } else {
-      const transparentPixels = new Uint8ClampedArray(width * height * 4)
-      gl.texImage2D(target, level, internalFormat, width, height, border, srcFormat, srcType, transparentPixels)
+      gl.texImage2D(target, level, internalFormat, width, height, border, srcFormat, srcType, null)
```
Comment (hiddenist) [inline libs/drawing-engine/src/engine/Layer.ts:49]:
```suggestion
      const transparentPixels = new Uint8ClampedArray(width * height * 4)
      gl.texImage2D(target, level, internalFormat, width, height, border, srcFormat, srcType, transparentPixels)
```

File: libs/drawing-engine/src/engine/DrawingEngine.ts [hunk 2]
```diff
@@ -187,9 +187,14 @@ export class DrawingEngine {
     return position[0] >= 0 && position[0] <= this.state.width && position[1] >= 0 && position[1] <= this.state.height
   }
 
-  public draw(drawCallback: () => void): this {
+  public draw(drawCallback: () => HistoryEntry | undefined): this {
```
Comment (hiddenist) [inline libs/drawing-engine/src/engine/DrawingEngine.ts:190]:
```suggestion
  public draw(drawCallback: () => HistoryItem | undefined): this {
```
